spendingtracker/category/routes.py
from flask import Blueprint, render_template, flash, request, url_for, redirect
from flask_login import login_required, current_user

from spendingtracker import db
from spendingtracker.category.forms import CategoryForm
from spendingtracker.models import Category, User

categorybp = Blueprint('category', __name__)


@categorybp.route('/add-category', methods=['GET', 'POST'])
@login_required
def add_cat():
    main_categories = Category.users_main_categories(curr_user=current_user)

    form = CategoryForm()
    form.main_category.choices = [("", "---")] + [(cat.id, cat.name) for cat in main_categories]
    if form.validate_on_submit() and request.method == 'POST':
        main_category_id = int(form.main_category.data) if form.main_category.data else None
        if Category.is_in_user_cat_set(form.name.data.capitalize()):
            flash(f"You have such Category already  : {form.name.data.capitalize()}", "danger")
            return redirect(url_for('category.add_cat'))
        category = Category.create_category(name=form.name.data.capitalize(),
                                            parent=Category.query.get(main_category_id),curr_user_id=current_user.id)
        flash(f"Added new Category : {category.name}", "info")
        return redirect(url_for('category.add_cat'))
    return render_template('add_category.html', form=form, main_categories=main_categories)


@categorybp.route('/all-category', methods=['GET', "POST"])
@login_required
def all_cat():
    all_cat = Category.query.all()
    return render_template("all_category.html", all_cat=all_cat)


@categorybp.route('/del-cat/<name>', methods=["GET", 'POST'])
@login_required
def del_cat(name):
    if name == 'Root':
        flash(f"Cannot Delete this category: {name}", 'danger')
        return redirect(url_for('category.add_cat'))
    cat_to_del = Category.is_in_user_cat_set(name=name)
    current_user.category_set.remove(cat_to_del)
    db.session.commit()
    flash(f"Category Deleted : {cat_to_del.name}", 'danger')
    return redirect(url_for('category.add_cat'))

spendingtracker/main/routes.py
from flask import Blueprint, render_template, current_app

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    map_site = ['%s' % rule for rule in current_app.url_map.iter_rules()]
    return render_template("layout.html", mapsite=[])

spendingtracker/products/routes.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template, flash, request, url_for, redirect, make_response
from flask_login import current_user, login_required
from sqlalchemy.orm import aliased

from spendingtracker import db
from spendingtracker.models import Category, ProductPurchased, User
from spendingtracker.products.forms import ProductForm

productbp = Blueprint('products', __name__)


@productbp.route('/all-products', methods=['GET', "POST"])
@productbp.route('/all-products/<period>', methods=['GET', "POST"])
@login_required
def all_prod(period=None):
    all_products = ProductPurchased.all_user_products_by_period(period)

    sumprice_of_product_each_subcat = ProductPurchased.sumprice_of_product_each_subcat()

    sumprice_of_product_each_subcat_tabchart_dict = {query_res[0]: str(query_res[1]) for query_res in
                                                     sumprice_of_product_each_subcat}

    sumprice_of_product_each_maincat = ProductPurchased.sumprice_of_product_each_maincat()
    sumprice_of_product_each_maincat_piechart_dict = {query_res[0]: str(query_res[1]) for query_res in
                                                      sumprice_of_product_each_maincat}

    return render_template("all_products.html", all_products=all_products,
                           sumprice_each_maincat_piechart_dict=sumprice_of_product_each_maincat_piechart_dict,
                           sumprice_of_product_each_subcat_tabchart_dict=sumprice_of_product_each_subcat_tabchart_dict)


@productbp.route('/add-product', methods=['GET', 'POST'])
@login_required
def add_product():
    user_subcat = Category.users_all_sub_categories(curr_user=current_user)

    recent_shopping = ProductPurchased.query.filter_by(user_id=current_user.id).limit(10).all()
    form = ProductForm()
    form.cat_of_purchase.choices = [("", "---")] + [(cat.id, cat.name) for cat in user_subcat]
    if form.validate_on_submit() and request.method == 'POST':
        product = ProductPurchased(price=form.price.data, purchased_by=current_user,
                                   purchase_cat=Category.query.get(int(form.cat_of_purchase.data)),
                                   buy_date=form.purchase_date.data)
        db.session.add(product)
        db.session.commit()
        flash(f"{product.purchase_cat}, added")
        return redirect(url_for('products.add_product'))
    return render_template('add_purchase.html', form=form, recent_shopping=recent_shopping)


@productbp.route('/del-prod/<int:id>', methods=["GET", 'POST'])
@login_required
def del_prod(id):
    prod_to_del = ProductPurchased.query.get_or_404(id)
    db.session.delete(prod_to_del)
    flash(f"{prod_to_del.purchase_cat.name}, deleted")
    db.session.commit()
    return redirect(url_for('products.all_prod'))

spendingtracker/users/routes.py
import os

from flask import Blueprint, url_for, redirect, render_template, flash, request
from flask_login import current_user, login_user, logout_user, login_required

from spendingtracker import bcrypt, db, s3_client
from spendingtracker.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from spendingtracker.models import User
from spendingtracker.users.utils import send_reset_email, save_picture, show_image

users=Blueprint("users",__name__)




@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)



@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password.encode('utf-8'), form.password.data.encode('utf-8')):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    # image_file = url_for('static', filename='profile_pic/' + current_user.image_file)
    image_file = show_image(current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)





@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

spendingtracker/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section main-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

spendingtracker/templates/add_category.html
{% extends "layout.html"%}

{%block content%}
<div class="row">
    <div class="col-md-8">
        <div class="content-section main-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Add Category</legend>

                    <div class="form-group">
                        {{ form.name.label(class="form-control-label") }}
                        {{ form.name(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group">
                        {{ form.main_category.label(class="form-control-label") }}
                        {{ form.main_category(class="form-control form-control-lg") }}
                    </div>
                    <div class="form-group mt-2">
                        {{ form.submit(class="btn btn-outline-dark btn-lg") }}
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <div class="col-md-4">
        <div class="content-section main-section">
            {%for cat in main_categories%}
            <div class="accordion" id="accordionExample">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapse{{loop.index}}" aria-expanded="false"
                                aria-controls="collapseOne">
                            {{cat.name}}
                        </button>

                    </h2>

                    <div id="collapse{{loop.index}}" class="accordion-collapse collapse " aria-labelledby="headingOne"
                         data-bs-parent="#accordionExample">
                        <div class="accordion-body border bg-secondary">
                            {{cat.name}}

                            <button type="button" class="btn fas fa-trash p-0" data-bs-toggle="modal"
                                    data-bs-target="#exampleModal"
                                    data-bs-whatever="{{cat.name}}">
                            </button>
                        </div>
                        {%for subcat in cat.users_subcategories(cat.name,curr_user=current_user)%}
                        <div class="accordion-body border">
                            <div>
                                <span>{{subcat}}</span>
                                <button type="button" class="btn fas fa-trash p-0" data-bs-toggle="modal"
                                        data-bs-target="#exampleModal"
                                        data-bs-whatever="{{subcat}}">
                                </button>
                            </div>
                        </div>
                        {%endfor%}
                    </div>

                </div>


            </div>
            {%endfor%}

        </div>
    </div>


    <!--{% for field, errors in form.errors.items() %}-->
    <!--<div class="alert alert-error">-->
    <!--    {{ form[field].label }}: {{ ', '.join(errors) }}-->
    <!--</div>-->

    <!--        {% endfor %}-->
    <!--        <div>-->
    <!--            {%for cat in main_categories%}-->
    <!--            {{cat.name}}<br>-->
    <!--            {{cat.users_subcategories(cat.name,current_user)}}<br>-->
    <!--            {%endfor%}-->
    <!--        </div>-->
    <!--        </div>-->
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Do you want to delete whole
                    category ?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <form method="POST" id="del-form">
                    {{ form.hidden_tag() }}
                    <input class="btn btn-secondary" type="submit" value="Delete">
                </form>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Back
                </button>

            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var exampleModal = document.getElementById('exampleModal')
exampleModal.addEventListener('show.bs.modal', function (event) {
  var button = event.relatedTarget
  var form = document.getElementById('del-form')
  form.action={{url_for('category.del_cat',name=cat_to_del)}} + button.getAttribute('data-bs-whatever')
})



</script>
{%endblock%}

spendingtracker/templates/all_category.html
{% extends "layout.html"%}

{%block content%}
<ul class="list-group">
    {% for cat in all_cat%}
    <li class="list-group-item">{{cat.name}}<span class="mx-5"><a href={{url_for('category.del_cat',name=cat.name)}}>Delete</a></span></li>
    {%endfor%}
</ul>
{%endblock%}

spendingtracker/templates/all_products.html
{% extends "layout.html"%}

{%block content%}
<div class="row">
    <div class="col-md-8">
        <div class="content-section main-section">
            <div class="sort-by">
                <div class="btn-group d-flex align-items-center m-1">
                    <a href="{{url_for('products.all_prod',period='today')}}" class="btn btn-primary" >Today</a>
                    <a href="{{url_for('products.all_prod',period='7days')}}"  class="btn btn-primary">Last 7 day</a>
                    <a href="{{url_for('products.all_prod',period='month')}}" class="btn btn-primary">Current Month</a>
                    <a href="{{url_for('products.all_prod',period='year')}}"  class="btn btn-primary">Current Year</a>
                    <a href="{{url_for('products.all_prod',period='all')}}"  class="btn btn-primary">All</a>
                </div>
            </div>
            <div class="table-shopping" >
                <table id="products-table" class="table table-hover table-bordered mh-10">
                    <thead>
                    <tr>
                        <th scope="col" style="width: 12%">Category</th>
                        <th scope="col">Price</th>
                        <th scope="col">Date</th>
                        <th scope="col" style="width: 6%">Options</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for prod in all_products %}
                    <tr>
                        <td>{{prod.purchase_cat.name}}</td>
                        <td>{{prod.price}}</td>
                        <td>{{prod.buy_date.strftime("%d/%m/%Y")}}</td>
                        <td>
                            <a class="btn fas fa-trash p-0" href={{url_for('products.del_prod',id=prod.id)}}></a>
                        </td>
                    </tr>
                    {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="content-section main-section">
            <h3 class="text-center">Current Month Shopping</h3>
            <div id="piechart_3d" class="w-auto mw-60 p-1"></div>
        </div>
        <div class="content-section main-section">
            <h3 class="text-center">Total Summary </h3>
            <div id="table_div"></div>
        </div>

    </div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
<!--table pie chart all -->
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
        ["cos", "mos"],
          {% for cat_name, sum_of_prod in sumprice_each_maincat_piechart_dict.items()%}
          ['{{cat_name}}', {{sum_of_prod}}],

          {%endfor%}
        ]);

        var options = {
          title: 'Category Spending',
          is3D: true,
          legend: 'right',
          ignoreBounds: true
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
        chart.draw(data, options);
      }
<!--table sumup all tablechart -->
    google.charts.load('current', {'packages':['table']});
    google.charts.setOnLoadCallback(drawTable);

      function drawTable() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Category');
        data.addColumn('string', 'Summary');


        {% for prod,sum_of_prod_cat in sumprice_of_product_each_subcat_tabchart_dict.items() %}
                data.addRows([
                  ['{{prod}}',"{{ sum_of_prod_cat }}"]
                ]);
          {%endfor%}
        var table = new google.visualization.Table(document.getElementById('table_div'));

        table.draw(data, {width: '100%', height: '100%'});
      }

<!--Table list-->
$(document).ready(function() {
    $('#products-table').DataTable({
        "lengthMenu": [ [8, 25, 50, -1], [8, 25, 50, "All"] ]
    });
} );







</script>

{%endblock%}

spendingtracker/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!--jquery-->
    <script
            src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    <title>Spendingtracker</title>
</head>
<body>

<nav class="navbar navbar-expand-sm navbar-dark bg-dark" aria-label="Third navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">SpendingTracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample03"
                aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
            <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('category.add_cat') }}">Manage
                        Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('products.add_product') }}">Add
                        Purchase</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('products.all_prod') }}">Shopping
                        Summary</a>
                </li>
                <!--                <li class="nav-item dropdown">-->
                <!--                    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-bs-toggle="dropdown"-->
                <!--                       aria-expanded="false">Dropdown</a>-->
                <!--                    <ul class="dropdown-menu" aria-labelledby="dropdown03">-->
                <!--                        <li><a class="dropdown-item" href="#">Action</a></li>-->
                <!--                        <li><a class="dropdown-item" href="#">Another action</a></li>-->
                <!--                        <li><a class="dropdown-item" href="#">Something else here</a></li>-->
                <!--                    </ul>-->
                <!--                </li>-->
            </ul>
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">{{current_user.username}}</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
            <!--            <form>-->
            <!--                <input class="form-control" type="text" placeholder="Search" aria-label="Search">-->
            <!--            </form>-->
        </div>
    </div>
</nav>

<div class="container">
    <div class="col-md-8 my-1 mx-auto">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    {% block content%}
    <div class="jumbotron bg-secondary rounded text-white p-2 text-center">
        <h1 class="display-4">Welcome to SpendingTracker</h1>

        <hr class="my-4">
        <p>This app helps you to manage your everyday spending</p>
        <p class="lead">
            {% if not current_user.is_authenticated %}
             <div class="my-2"><i class="fas fa-dollar-sign fa-7x"></i></div>
            <a class="btn btn-secondary" href="{{ url_for('users.login') }}">Log In</a>
            {%endif%}
        </p>
    </div>

    {% for route in mapsite%}
    {{route}}
    <br>
    {% endfor %}
    {% endblock %}

</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
        integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
        integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
        crossorigin="anonymous"></script>
<!--fontawsome-->
<script src="https://kit.fontawesome.com/dd44f93866.js" crossorigin="anonymous"></script>
<!--datatable-->
<script src="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.min.css" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
</body>
</html>

spendingtracker/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section main-section m-1 p-2">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-dark ") }}
            </div>
<!--            <small class="text-muted ml-2">-->
<!--                <a href="#">Forgot Password?</a>-->
<!--            </small>-->
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
<!--{% for field, errors in form.errors.items() %}-->
<!--<div class="alert alert-error">-->
<!--    {{ form[field].label }}: {{ ', '.join(errors) }}-->
<!--</div>-->
{% endfor %}
{% endblock content %}